version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
  
  backend:
    image: krishnadas7/eventhive-backend:latest
    container_name: backend
    ports:
      - '3003:3003'
    env_file:
      - .env
    depends_on:
      - redis