export interface ICompany{
    _id?:string;
    company_name?:string;
    company_email?:string;
    password?:string;
    company_logo?:string;
    confirm_password?:string;
    is_block?:Boolean;
    contact_personname?:string;
    contact_personphone?:string;
    company_website?:string;
    company_address?:string;
    city?:string;
    state?:string;
    postal_code?:string;
    otp?:string;
    locality?:string;
    country?:string;
    industry_type?:string;
    company_description?:string;
    profileImage?:string;
}